### PR TITLE
fix: Fix bug that prevented using keyboard shortcuts when the DropDownDiv is open.

### LINKED ISSUE #522: Escape no longer reliably closes field editors
In local builds of the demo, it seems to work only for the first colour picker and never for dropdowns.

The [pre-focus-changes version currently deployed](https://google.github.io/blockly-keyboard-experimentation/) works reliably in this respect.

### PR DESCRIPTION
**Pull request by gonfunko**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes https://github.com/google/blockly-keyboard-experimentation/issues/522

### Proposed Changes
This PR moves the attachment of the global keyboard shortcut handler to the `DropDownDiv` and `WidgetDiv` into those respective modules, rather than adding the listener in `inject()`. This reduces spooky action at a distance, and fixes a bug caused by a change to the `DropDownDiv` to make it recreate its div between showings in order to guarantee that its state is fully reset. Because the key handler was attached elsewhere, this being unsafe wasn't noticed. Now, the listener is added every time the div is created, and the logic to attach it has been moved into the relevant modules themselves to hopefully avoid being overlooked in a similar manner in the future.

### CODE REVIEW

File: core/common.ts [hunk 1]
```diff
@@ -310,4 +312,31 @@ export function defineBlocks(blocks: {[key: string]: BlockDefinition}) {
...
 }
 
+/**
+ * Handle a key-down on SVG drawing surface. Does nothing if the main workspace
+ * is not visible.
+ *
+ * @internal
+ * @param e Key down event.
+ */
+// TODO (https://github.com/google/blockly/issues/1998) handle cases where there
```
Comment (BenHenning) [inline core/common.ts]: This appears out of date. Is it still relevant? If so, perhaps we should file a new issue and update this accordingly.

File: core/widgetdiv.ts [hunk 2]
```diff
@@ -69,11 +70,19 @@ export function createDom() {
   if (document.querySelector('.' + containerClassName)) {
     containerDiv = document.querySelector('.' + containerClassName);
   } else {
-    containerDiv = document.createElement('div') as HTMLDivElement;
+    containerDiv = document.createElement('div');
     containerDiv.className = containerClassName;
   }
+  if (!containerDiv) return;
```
Comment (BenHenning) [inline core/widgetdiv.ts]: Is this case actually possible or just TS not knowing that it isn't? The code above seems to guarantee the div will exist, so perhaps the code could be rearranged to ensure that TS is aware of the value being present in order to obviate this check.

**Review by BenHenning — COMMENTED** [review]
Thanks @gonfunko! The fix makes a lot of sense, and does seem to improve robustness overall.

Is it possible to test the failure cases for both divs and verify that the fix addresses the issue? I'm not sure how difficult that would be, but this seems like a thing that's very subtle and could potentially break again without some sort of regression check.

File: core/common.ts (hunk 1 above)
Comment (gonfunko) [reply core/common.ts]: Removed.

File: core/widgetdiv.ts (hunk 2 above)
Comment (gonfunko) [reply core/widgetdiv.ts]: Mostly TS not knowing; refactored so that it does.

**Review by BenHenning — APPROVED** [review]
Thanks @gonfunko! LGTM.
