### PR TITLE
fix: Don't close the flyout when creating a variable using keyboard nav

### LINKED ISSUE #9122: Creating a variable closes the flyout
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

Creating a variable via mouse or keyboard causes the flyout to close. This seems to be related to [this change](https://github.com/google/blockly/pull/9079/files#diff-59828f52fe91a917c7cbcc9d82c06427307f6cc1d7d1431bf4030d39a27415a6R1147-R1156). This may need a similar fix to https://github.com/google/blockly/pull/9116, however, it might be hard to know what to focus as the dialogs can be customised. Multiple dialogs can also appear in succession (e.g., when trying to create a variable that already exists).

Note: for some reason, if you have dev tools open, the flyout stays open.

### Reproduction steps

1. 
2. 
3.

### Stack trace

```shell

```

### Screenshots

_No response_

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by gonfunko**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #9122

### Proposed Changes
This PR updates Blockly's `dialog` utility to use a `<dialog>` element instead of the built-in browser alert modals. This allows for more consistent focus management, since the dialog is just part of the DOM rather than an application-level modal. Secondarily, it adds an event listener to the flyout workspace in the create variable button callback handler that identifies and focuses the newly-created variable block for convenience now that the flyout no longer closes.

### CODE REVIEW

File: packages/blockly/core/dialog.ts [hunk 1]
```diff
@@ -165,3 +172,111 @@ export function setToast(
...
   toastImplementation = toastFunction;
 }
+
+/**
+ * Displays a dialog, potentially prompting for user input, and invokes the
+ * provided callback with the response.
+ */
+function displayDialog(
+  ...[type, message, callback, defaultValue]:
+    | [
```
Comment (maribethb) [inline packages/blockly/core/dialog.ts:182]: I wonder if function overloading would be more readable than this? you'd be able to have better docs on the parameters as well.

File: packages/blockly/core/dialog.ts [hunk 2]
```diff
@@ -23,7 +32,7 @@ const defaultConfirm = function (
   message: string,
   callback: (result: boolean) => void,
 ) {
-  callback(window.confirm(message));
+  displayDialog(DialogType.CONFIRM, message, callback, undefined);
```
Comment (maribethb) [inline packages/blockly/core/dialog.ts:35]: Are you sure that ephemeral focus shouldn't be marked taken and then released in the callback? I know for the flyout use case you're somewhat manually restoring focus so that might be fine, but in the general case in order to restore focus correctly I think you might want this? Plus, some of the shortcuts specifically check if ephemeral focus is taken in their precondition

**Review by maribethb — COMMENTED** [review]
1 question about ephemeral focus, and then also want to double check there's no behavioral change for developers who are calling our prompt functions right? so this isn't breaking?

File: packages/blockly/core/dialog.ts (hunk 1 above)
Comment (gonfunko) [reply packages/blockly/core/dialog.ts:182]: I tried that initially but TS can't infer the types of the callback arguments based on the type of dialog, whereas with this approach it can.

File: packages/blockly/core/dialog.ts (hunk 2 above)
Comment (gonfunko) [reply packages/blockly/core/dialog.ts:35]: It is taken in the implementation of `displayDialog()` (line 255). I just tweaked that to take it for the dialog vs the focused element since I think that's the design intent and may be helpful for the focus-lost-outside-the-div situation.

**Comment by gonfunko** [comment]
Correct, there should be no functional behavior difference - same API calls work, the contents are just displayed in our custom dialog vs the browser modal. And it's still possible for developers to replace our implementation with their own.

File: packages/blockly/core/dialog.ts [hunk 3]
```diff
@@ -165,3 +172,109 @@ export function setToast(
...
+    cancel.value = CANCEL;
+    buttonRow.appendChild(cancel);
+  }
+
+  form.appendChild(buttonRow);
+
+  const focusedNode = getFocusManager().getFocusedNode();
+  let restoreFocus: (() => void) | undefined;
+  if (focusedNode && activeDialogCount === 0) {
+    restoreFocus = getFocusManager().takeEphemeralFocus(dialog);
```
Comment (maribethb) [inline packages/blockly/core/dialog.ts:254]: thanks, missed it here. this makes sense to me. `dialog` is the correct thing that should be taking ephemeral focus. so i think you can leave off the condition of if there is already a focused node. the focus manager should handle it correctly either way.

**Review by maribethb — APPROVED** [review]

File: packages/blockly/core/dialog.ts (hunk 3 above)
Comment (gonfunko) [reply packages/blockly/core/dialog.ts:254]: Whoops yeah missed removing that, thanks!

**Comment by gonfunko** [comment]
This also fixed #9106.
