### PR TITLE
fix: add group when cutting workspace comments

### LINKED ISSUE #9164: events not grouped correctly for cut/paste
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

When a block or workspace comment (or other `ICopyable` thing) is cut or pasted, several events are fired at once:

for cut
- Selected (old: block id, new: null)
- Delete block or delete comment

for paste, or duplicate context menu option
- selected (old: whatever was previously selected, new: id of pasted thing)
- Create block or create comment

These two events should be grouped since they are part of the same user action. They are only grouped for the case of cutting a block specifically, because the cut callback calls a block's `checkAndDelete` method which handles event grouping. For the case of cutting other non-block types, or pasting anything including blocks, or using the duplicate context menu item, there is no group id set on the events fired in those cases.

### Reproduction steps

1. Enable event logging in the playground
2. Cut a block with ctrl+x and notice the events fired have a group id
3. Cut a workspace comment with ctrl-x and notice they don't

### Stack trace

```shell

```

### Screenshots

_No response_

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by lizschwab**
## The basics

- [ x ] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes https://github.com/RaspberryPiFoundation/blockly/issues/9164

### Proposed Changes

Adds an event group when the `cut` action is performed from a keyboard shortcut for a non-block entity.
image

### Reason for Changes

Without this functionality, events fired from the `cut` keyboard shortcut cannot be grouped together.

### CODE REVIEW

File: packages/blockly/core/shortcut_items.ts [hunk 1]
```diff
@@ -217,7 +217,9 @@ export function registerCut() {
       if (focused instanceof BlockSvg) {
         focused.checkAndDelete();
       } else if (isIDeletable(focused)) {
+        eventUtils.setGroup(true);
         focused.dispose();
+        eventUtils.setGroup(true);
```
Comment (mikeharv) [inline packages/blockly/core/shortcut_items.ts]: Should this second call be `setGroup(false)`? I see a similar pattern used in `registerDelete()` and in `registerCommentDelete()` (from `contextmenu_items.ts`).

Comment (lizschwab) [reply packages/blockly/core/shortcut_items.ts]: Whoops, you're correct. Looks like I missed that when I had to re-apply the changes after fixing a git issue I was having. Thanks for catching that!

**Review by maribethb — APPROVED** [review]
