### PR TITLE
fix: Fix more browser tests

### LINKED ISSUE #8953: Browser tests fail with "element not interactable"
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

Browser tests fail after collapsing a block.

My guess is that there's an issue with `clickBlock` but I have not dug deeper yet.

```
/**
 * Find a clickable element on the block and click it.
 * We can't always use the block's SVG root because clicking will always happen
 * in the middle of the block's bounds (including children) by default, which
 * causes problems if it has holes (e.g. statement inputs). Instead, this tries
 * to get the first text field on the block. It falls back on the block's SVG root.
 * @param browser The active WebdriverIO Browser object.
 * @param block The block to click, as an interactable element.
 * @param clickOptions The options to pass to webdriverio's element.click function.
 * @return A Promise that resolves when the actions are completed.
 */
export async function clickBlock(browser, block, clickOptions) {
  const findableId = 'clickTargetElement';
  // In the browser context, find the element that we want and give it a findable ID.
  await browser.execute(
    (blockId, newElemId) => {
      const block = Blockly.getMainWorkspace().getBlockById(blockId);
      for (const input of block.inputList) {
        for (const field of input.fieldRow) {
          if (field instanceof Blockly.FieldLabel) {
            field.getSvgRoot().id = newElemId;
            return;
          }
        }
      }
      // No label field found. Fall back to the block's SVG root.
      block.getSvgRoot().id = findableId;
    },
    block.id,
    findableId,
  );

  // In the test context, get the Webdriverio Element that we've identified.
  const elem = await browser.$(`#${findableId}`);

  await elem.click(clickOptions);

  // In the browser context, remove the ID.
  await browser.execute((elemId) => {
    const clickElem = document.getElementById(elemId);
    clickElem.removeAttribute('id');
  }, findableId);
}
```

### Reproduction steps

1. Check out `rc/v12.0.0`
2. Build
3. Run `npm run test:browser`
4. Observe failures in the terminal

### Stack trace

```shell
Right Clicking on Blocks
    ✔ clicking the collapse option collapses the block (293ms)
2025-05-01T18:35:24.083Z WARN webdriver: WebDriverError: element not interactable: [object SVGGElement] has no size and location
```

### Screenshots

_No response_

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by RoboErikG**
## The basics

This fixes the remaining browser tests

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes [#8953](https://github.com/google/blockly/issues/8953)

### Proposed Changes

Lots of fixes to the browser tests

### CODE REVIEW

File: tests/browser/test/delete_blocks_test.mjs [hunk 1]
```diff
@@ -194,7 +194,8 @@ suite('Delete blocks', function (done) {
     );
   });
 
-  test('Redo block deletion', async function () {
+  // TODO(#9029) enable this test once deleting a block doesn't lose focus
```
Comment (gonfunko) [inline tests/browser/test/delete_blocks_test.mjs]: This was fixed in https://github.com/google/blockly/pull/9195, can this be reenabled now?

File: tests/browser/test/test_setup.mjs [hunk 2]
```diff
@@ -295,6 +298,55 @@ export async function getBlockTypeFromCategory(
...
+  // In the browser context, find the element that we want and give it a findable ID.
+  await browser.execute(
+    (blockType, newElemId) => {
+      const block = Blockly.getMainWorkspace()
+        .getFlyout()
+        .getWorkspace()
+        .getBlocksByType(blockType)[0];
+      if (!block.isCollapsed()) {
+        for (const input of block.inputList) {
+          for (const field of input.fieldRow) {
```
Comment (gonfunko) [inline tests/browser/test/test_setup.mjs]: There's a recently-ish introduced `getFields()` that returns a generator that might be more convenient here, but not a blocker.

File: tests/browser/test/test_setup.mjs [hunk 3]
```diff
@@ -448,6 +500,9 @@ export async function switchRTL(browser) {
  */
 export async function dragNthBlockFromFlyout(browser, categoryName, n, x, y) {
   const flyoutBlock = await getNthBlockOfCategory(browser, categoryName, n);
+  while (!(await elementInBounds(browser, flyoutBlock))) {
+    await scrollFlyout(browser, 0, 50);
+  }
```
Comment (gonfunko) [inline tests/browser/test/test_setup.mjs]: Could you use `WorkspaceSvg.scrollBoundsIntoView(flyoutBlock.getBoundingRectangleWithoutChildren())` rather than scrolling repeatedly by a fixed amount until it's on screen?

File: tests/browser/test/test_setup.mjs [hunk 4]
```diff
@@ -474,15 +529,44 @@ export async function dragBlockTypeFromFlyout(
...
 ) {
-  const flyoutBlock = await getBlockTypeFromCategory(
+  const flyoutBlock = await getDraggableBlockElementByType(
     browser,
     categoryName,
     type,
   );
+  while (!(await elementInBounds(browser, flyoutBlock))) {
+    await scrollFlyout(browser, 0, 50);
+  }
```
Comment (gonfunko) [inline tests/browser/test/test_setup.mjs]: Here as well

File: tests/browser/test/test_setup.mjs (hunk 3 above)
Comment (gonfunko) [reply tests/browser/test/test_setup.mjs]: This would seemingly allow you to get rid of `elementInBounds`, since it should be safe to do unconditionally.

File: tests/browser/test/toolbox_drag_test.mjs [hunk 5]
```diff
@@ -57,28 +57,29 @@ const testCategories = [
...
+    return Blockly.getMainWorkspace()
+      .getFlyout()
+      .getWorkspace()
+      .getTopBlocks(false)[i].type;
+  }, n);
 
-    return vertInView && horInView;
-  }, element);
+  // Unicode escape to close flyout.
+  await browser.keys(['\uE00C']);
```
Comment (gonfunko) [inline tests/browser/test/toolbox_drag_test.mjs]: Can this be `webdriverio.Key.Escape`?

File: tests/browser/test/delete_blocks_test.mjs (hunk 1 above)
Comment (RoboErikG) [reply tests/browser/test/delete_blocks_test.mjs]: Done.

File: tests/browser/test/test_setup.mjs (hunk 2 above)
Comment (RoboErikG) [reply tests/browser/test/test_setup.mjs]: Done.

File: tests/browser/test/test_setup.mjs (hunk 3 above)
Comment (RoboErikG) [reply tests/browser/test/test_setup.mjs]: It took some reworking of a few of the test methods, but does seem to be cleaner and work better overall. =)

File: tests/browser/test/toolbox_drag_test.mjs (hunk 5 above)
Comment (RoboErikG) [reply tests/browser/test/toolbox_drag_test.mjs]: Done here and elsewhere.

**Review by RoboErikG — COMMENTED** [review]
Updated based on comments

**Review by gonfunko — APPROVED** [review]
