### PR TITLE
fix: Improve representation of `FlyoutButtons` in screenreaders.

### LINKED ISSUE #9294: FlyoutButton has a hardcoded aria-label of "Button"
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

Using https://google.github.io/blockly-keyboard-experimentation/screenreader/ flyout labels and buttons read out poorly because of hardcoded incorrect label text.

### Reproduction steps

1. Use https://google.github.io/blockly-keyboard-experimentation/screenreader/
2. Note that the text "This is a label" in category Misc has role="button" and aria-label="Button" 
3. Note that the button "Create Variable" has the same aria label (role is good here)

They both get read as "button Button" or similar across screen readers.

(2) is particularly important in MakeCode as all categories have a label at the top.

As the text is correct already likely we can just remove the aria-labels in both cases and test with screen readers (OK in VoiceOver at least).

For the label maybe role=heading with the correct heading level passed from the application as Blockly doesn't have sufficient context to set the level correctly. In MakeCode there are headings for the category as a whole and for subsections of the category. But any role that resulted in the label text being read out would be a step forward.

### Stack trace

```shell

```

### Screenshots

_No response_

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by gonfunko**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #9294

### Proposed Changes
This PR updates `FlyoutButton`s to use either a `button` or `treeitem` ARIA role based on whether they are acting as buttons or labels. The actual text will be read out in both cases, and it will be denoted as a button when it is one.

### Limitations
At least on VoiceOver, the screenreader focus ring targets the whole flyout for the button variant, and the selection status is not spoken. Neither is an issue for labels.

### CODE REVIEW

File: core/flyout_button.ts [hunk 1]
```diff
@@ -406,10 +416,13 @@ export class FlyoutButton
     const xy = this.getPosition();
     const bounds = new Rect(xy.y, xy.y + this.height, xy.x, xy.x + this.width);
     this.workspace.scrollBoundsIntoView(bounds);
+    aria.setState(this.svgGroup, aria.State.SELECTED, true);
```
Comment (maribethb) [inline core/flyout_button.ts]: I don't think `aria-selected` makes sense here, maybe that's why VO doesn't read it out. I think `aria-selected` is supposed to be used for like, custom radio buttons or something like that where they have a selected state. But here are you just using it to show that it's focused? I don't think you need to set the selected state for that. It being focused is enough. These buttons don't have state.

I found an issue that seems to imply that VO would respect aria-pressed for buttons, but I don't think that's appropriate either for the same reasons.

File: core/flyout_button.ts [hunk 2]
```diff
@@ -135,6 +140,7 @@ export class FlyoutButton
         },
         this.svgGroup!,
       );
+      aria.setRole(shadow, aria.Role.PRESENTATION);
```
Comment (maribethb) [inline core/flyout_button.ts:143]: I hate that you have to do this but I don't know enough to suggest anything better. There is *very* little out there in terms of mark up for VO specifically.

File: core/flyout_button.ts (hunk 1 above)
Comment (gonfunko) [reply core/flyout_button.ts]: That makes sense; I added it for consistency with blocks, which do get read out as "selected", but I think you're right and that behavior is the bug – obviously it's selected because the screenreader is reading it out! Removed accordingly.

File: core/flyout_button.ts (hunk 2 above)
Comment (gonfunko) [reply core/flyout_button.ts:143]: Agreed. Happy to revisit down the line if we find a better alternative though.

File: core/flyout_button.ts (hunk 1 above)
Comment (maribethb) [reply core/flyout_button.ts]: For blocks I could see it being useful in cases where selection != focus (e.g. for multiselect) so we might have to find a way to overcome the fact that VO won't let you use aria-selected for arbitrary roles. But, that is a different problem and I don't think it applies to flyout buttons regardless.

**Review by maribethb — APPROVED** [review]
