### PR TITLE
fix: Correct the alignment of narrow text in input fields.

### LINKED ISSUE #9069: The position of `text` elements in blocks is wrong
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

The position of `text` elements in blocks is wrong. It's actually the amount of transform on the parent `g` element of the `text` element. They used to be central, but are now rendered slightly to the left. 

It is very noticeable when you start and stop editing the field.

### Reproduction steps

1. 
2. 
3.

### Stack trace

```shell

```

### Screenshots

https://github.com/user-attachments/assets/71fca41f-08ee-4bae-be07-aaad88ab96a7

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by gonfunko**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #9069

### Proposed Changes
This PR fixes a bug that caused narrow text values in Zelos input fields to be slightly misaligned horizontally from the center. Input fields have a minimum width, and if the measured width of the text was less than that, it was positioned incorrectly. I also adjusted a couple places that were manually setting the `width` attribute of the field size and bypassing the minimum size enforcement as a result; this wasn't a root cause, but could lead to tricky bugs down the line.

### CODE REVIEW

File: core/field_input.ts [hunk 1]
```diff
@@ -732,6 +737,23 @@ export abstract class FieldInput<T extends InputTypes> extends Field<
     return true;
   }
 
+  /**
+   * Position a field's text element after a size change.  This handles both LTR
+   * and RTL positioning.
+   *
+   * @param xOffset x offset to use when positioning the text element.
```
Comment (RoboErikG) [inline core/field_input.ts]: Consider renaming xMargin and clarifying in comment that this is added to both sides of the element. Since you're adding it to both sides and centering the text element it's not exactly an offset.

**Review by RoboErikG — APPROVED** [review]
One comment on naming/comments but otherwise LGTM.

File: core/field_input.ts (hunk 1 above)
Comment (gonfunko) [reply core/field_input.ts]: Done.
